# APIとは
APIとは Application Programming Interfaceの略。 ソフトウェアからOSの機能を利用するための仕様またはインターフェースの総称で、アプリケーションの開発を容易にするためのソフトウェア資源のことをいう。

# API演習

In [37]:
!pip install newsapi-python
from newsapi import NewsApiClient    
from pprint import pprint

newsapi = NewsApiClient(api_key='000000000000000000000000')    

top_headlines = newsapi.get_top_headlines(q='コロナ',language=None, country='jp')

pprint(top_headlines)

Requirement already satisfied: newsapi-python in c:\users\kouta\anaconda3\lib\site-packages (0.2.6)
Requirement already satisfied: requests<3.0.0 in c:\users\kouta\anaconda3\lib\site-packages (from newsapi-python) (2.26.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kouta\anaconda3\lib\site-packages (from requests<3.0.0->newsapi-python) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kouta\anaconda3\lib\site-packages (from requests<3.0.0->newsapi-python) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\kouta\anaconda3\lib\site-packages (from requests<3.0.0->newsapi-python) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\kouta\anaconda3\lib\site-packages (from requests<3.0.0->newsapi-python) (1.26.7)
{'articles': [{'author': None,
               'content': '83324100049134077123',
               'description': '大阪府は8日、新たに3324人が新型コロナウイルスに感染していることが確認されたと発表しました。前の週の同じ曜日と比べて…',
               'publishedAt': '2022-05-08T09:10:13Z',
               'source': {'id': None, 'name': 'Nhk.or.jp'},
               'title': '大阪府 新型コロナ 新たに3324人感染確認 - nhk.or.jp',
               'url': 'https://www3.nhk.or.jp/news/html/20220508/k10013616251000.html',
               'urlToImage': 'https://www3.nhk.or.jp/news/html/20220508/K10013616251_2205081753_0508181014_01_02.jpg'},
              {'author': None,
               'content': '81150026\r\n'
                          '8101004711\r\n'
                          '115002\r\n'
                          '873182.975.1\r\n'
                          '847112024.51156\r\n'
                          '652755.8\r\n'
                          'ECMO887\r\n'
                          '70906',
               'description': '東京都内の8日の感染確認は、1週間前の日曜日よりおよそ1500人増え、2日連続で前の週の同じ曜日を上回りました。また、都…',
               'publishedAt': '2022-05-08T08:58:49Z',
               'source': {'id': None, 'name': 'Nhk.or.jp'},
               'title': '東京都 新型コロナ 6人死亡 4711人感染 2日連続で前週を上回る - nhk.or.jp',
               'url': 'https://www3.nhk.or.jp/news/html/20220508/k10013615961000.html',
               'urlToImage': 'https://www3.nhk.or.jp/news/html/20220508/K10013615961_2205081607_0508165020_01_02.jpg'},
              {'author': '福島民報',
               'content': None,
               'description': '福島県は県内で５９９人の新型コロナウイルス感染が確認されたと８日、発表した。前週の日曜日発表分と比べて３２４人多かった。５９９人の感染は７日に判明した。居住地の内訳は郡山市が１４１人、福島市が９５人…',
               'publishedAt': '2022-05-08T02:25:00Z',
               'source': {'id': None, 'name': 'Minpo.jp'},
               'title': '＜速報＞福島県内５９９人感染確認 新型コロナ（８日発表） | 福島民報 - 福島民報',
               'url': 'https://www.minpo.jp/news/moredetail/2022050896842',
               'urlToImage': 'https://www.minpo.jp/common/img/news/2022050896842_0.jpg'},
              {'author': None,
               'content': None,
               'description': '島根県と鳥取県は７日、それぞれ１３８人、１３４人が新型コロナウイルスに感染したと発表した。いずれも６日の確認分。松江市内の学校の部活動でクラスター（感染者集団）が確認された。  \u3000'
                              '島根県の居住地別は松…',
               'publishedAt': '2022-05-07T19:00:00Z',
               'source': {'id': None, 'name': 'Sanin-chuo.co.jp'},
               'title': '島根１３８人、鳥取１３４人コロナ感染 松江で部活クラスター - 山陰中央新報社',
               'url': 'https://www.sanin-chuo.co.jp/articles/-/204203',
               'urlToImage': 'https://sanin-chuo.ismcdn.jp/mwimgs/4/9/-/img_4954b2ed4d388ce46e566461d4c6b64b616676.jpg'},
              {'author': '産経新聞',
               'content': None,
               'description': '【北京＝三塚聖平】ホンダは７日、中国市場における４月の新車販売台数が、前年同月比３６・３％減の９万５２１６台だったと発表した。新型コロナウイルスの感染拡大により上海市などでロックダウン（都市封鎖）が続',
               'publishedAt': '2022-05-07T05:42:00Z',
               'source': {'id': None, 'name': 'Livedoor.com'},
               'title': 'ホンダ、4月の中国販売36％減 上海封鎖で供給網が混乱したことが影響 - ライブドアニュース - '
                        'livedoor',
               'url': 'https://news.livedoor.com/topics/detail/22124167/',
               'urlToImage': 'https://image.news.livedoor.com/newsimage/stf/f/6/f61b3_368_17145a0cbdf5d6d0c860e96e981527dd.jpg'}],
 'status': 'ok',
 'totalResults': 5}

# webスクレイピング
ウェブスクレイピングとは、ウェブサイトから情報を抽出するコンピュータソフトウェア技術のこと。

# webスクレイピング演習

In [29]:
from time import sleep
import re
from bs4 import BeautifulSoup
import requests
import pandas as pd

url = 'https://suumo.jp/chintai/tokyo/sc_shinjuku/?page{}'

In [46]:
d_list = []

for i in range(1, 5):
    print('d_listの大きさ：', len(d_list))
    target_url=url.format(i)

    r=requests.get(target_url)

    sleep(1)

    soup=BeautifulSoup(r.text)

    contents=soup.find_all('div',class_="cassetteitem")    

    for content in contents:

        detail=content.find('div',class_='cassetteitem-detail')

        table=content.find('table',class_='cassetteitem_other')

        title=detail.find('div',class_='cassetteitem_content-title').text
        
        address=detail.find('li',class_='cassetteitem_detail-col1').text

        access=detail.find('li',class_='cassetteitem_detail-col2').text

        age=detail.find('li',class_='cassetteitem_detail-col3').text


        tr_tags=table.find_all('tr',class_="js-cassette_link")    
        
        for tr_tag in tr_tags:
            
            floor, price, first_fee, capacity = tr_tag.find_all('td')[2:6]
            
            fee, management_fee = price.find_all('li')
            deposit, gratuity = first_fee.find_all('li')
            madori, menseki = capacity.find_all('li')
            
            d = {
                'title': title,
                'address': address,
                'access': access,
                'age': age,
                'floor': floor.text,
                'fee': fee.text,
                'management_fee': management_fee.text,
                'deposit': deposit.text,
                'gratuity': gratuity.text,
                'madori': madori.text,
                'menseki': menseki.text
            }    
            
            d_list.append(d)

d_listの大きさ： 0
d_listの大きさ： 147
d_listの大きさ： 294
d_listの大きさ： 441

In [45]:
import pandas as pd
df = pd.DataFrame(d_list)
df.head()

,title,address,access,age,floor,fee,management_fee,deposit,gratuity,madori,menseki
0,都営大江戸線 西新宿五丁目駅 3階建 築26年,東京都新宿区西新宿４,\n都営大江戸線/西新宿五丁目駅 歩5分\n京王新線/初台駅 歩11分\nＪＲ山手線/新宿駅...,\n築26年\n3階建\n,\r\n\t\t\t\t\t\t\t\t\t\t\t1-3階,48万円,-,48万円,24万円,7LDK,130.47m2
1,都営大江戸線 西新宿五丁目駅 3階建 築26年,東京都新宿区西新宿４,\n都営大江戸線/西新宿五丁目駅 歩5分\n京王新線/初台駅 歩11分\nＪＲ山手線/新宿駅...,\n築26年\n3階建\n,\r\n\t\t\t\t\t\t\t\t\t\t\t1-3階,48万円,-,48万円,24万円,7LDK,130.47m2
2,ザ・パークハウス市谷加賀町,東京都新宿区市谷加賀町２,\n都営大江戸線/牛込柳町駅 歩4分\n都営新宿線/曙橋駅 歩12分\n東京メトロ東西線/神...,\n築9年\n地下1地上5階建\n,\r\n\t\t\t\t\t\t\t\t\t\t\t5階,35万円,25000円,35万円,35万円,3LDK,84.27m2
3,ザ・パークハウス市谷加賀町レジデンス,東京都新宿区市谷加賀町１,\n都営大江戸線/牛込柳町駅 歩6分\n都営大江戸線/牛込神楽坂駅 歩8分\n東京メトロ南北...,\n新築\n地下1地上7階建\n,\r\n\t\t\t\t\t\t\t\t\t\t\t1階,32万円,15000円,64万円,32万円,2LDK,60.37m2
4,ザ・パークハウス市谷加賀町レジデンス,東京都新宿区市谷加賀町１,\n都営大江戸線/牛込柳町駅 歩6分\n都営大江戸線/牛込神楽坂駅 歩8分\n東京メトロ南北...,\n新築\n地下1地上7階建\n,\r\n\t\t\t\t\t\t\t\t\t\t\t3階,34.5万円,-,34.5万円,34.5万円,2LDK,60.37m2